### ISSUE TITLE
Feature request: GenericAgent should offer "not equal" option

### ISSUE THREAD

**Issue by ggrein** [znuny/znuny-feature-requests#1]
When implementing GA rules that should cover almost all of your queues, but exclude "Queue_X" and "Queue_Z", you have to select the whole list excluding these dedicated ones. 
In case you implement another queues you have to keep in mind that you also need to update the GA rules accordingly.
It would be much more convenient if it was possible to tell GA to run only if the queue is not "Queue_X" and not "Queue_Z".

**Comment by rkaldung** [comment]
This issues is closed because it is a duplicate if #5
