### ISSUE TITLE
Feature Request: Generic agent shall be able to have a more sophisticated AND/OR combination of fields

### ISSUE THREAD

**Issue by dpalic** [znuny/znuny-feature-requests#10]
Provide possibility to define AND, OR, NOT conditions for fields.

right now the GA has the problem, that you cannot match multiple e-mail addresses, or multiple subjects, see also a part of this feature request in znuny/znuny-feature-requests#14 

assume following case:
- client addresses are not stable underneath one domain, so you have tonline, gmx, gmail, web.de and so on, you need to be able to specifically name the user e-mail addresses

Now assume you need to match user-e-mails by topic and by e-mail address. You need to move the e-mails/tickets into the right queues
you would need to create GAs
- 1x GA per e-mail address for sending from Znuny
- 1x GA per e-mail address for receiving 
- 1x GA per topic to move to queue

Assume you have 5 clients, each 1 e-mail address and 3 possible topics, you would have to create
5 clients * 2 (one for sending and receiving) *3 = 30 GAs right now
Sadly this is fact for us right now

It could be solved if you could define in GA which allowes NOT, OR, AND conditions
this would reduce the GA amount on 3 GAs at all because you could define
```
(TO: client1adr OR client2adr OR client3adr)  // this could be a regex see znuny/znuny-feature-requests#14 
OR
(
   FROM: client1adr OR client2adr OR client3adr  // this could be a regex see znuny/znuny-feature-requests#14 
   AND
   subject: *topic1*
)
```
we have such requirements from daily business:
1. it ensures, even if an agent chooses a wrong queue, that the ticket is moved to right place
2. it ensures, that all cleint requests are assigned to the right queue
Right now we have to create a bunch of GAs, which makes the GA overview really unhandy, since tons of GAs are created due to lack of logical operations in GA

**suggestion**

a UI for this could be: like 
https://ux.stackexchange.com/q/92177
https://softwarerecs.stackexchange.com/q/14447 here it shows if/then instead it could be AND/OR/NOT
using http://angular-ui-tree.github.io/angular-ui-tree/#/filter-nodes

**Comment by rkaldung** [comment]
This issues is closed because it is nearly a duplicate if https://github.com/znuny/znuny-feature-requests/issues/5. Please check the other feature request for being updated.
