### ISSUE TITLE
Feature request - Show default only the customer's open tickets by default

### ISSUE THREAD

**Issue by falkos** [znuny/znuny-feature-requests#11]
### Environment

- OS:           MacOS
- Browser:      Safari
- Znuny version: 6.1.2

### Expected behaviour

In case i click to the Link-Button in the AgentTicketZoom i see 50 random Tickets. I would expect that i only see the Tickets from the Custumer of the Ticket by default. 

### Actual behaviour

I see 50 random Tickets.

### How to reproduce

You can see it at the screenshot. 

### Additional information

I "fixed" this problem at my system by adding "SourceCustomer=[% Data.CustomerID | html %]" to the sytem config item "Ticket::Frontend::MenuModule###320-Link" and created the files /opt/otrs/Custom/Kernel/Output/HTML/LinkObject/Ticket.pm and /opt/otrs/Custom/Kernel/Modules/AgentLinkObject.pm. Now i have the colume customerID in the search form and a default is set. 

[changes.zip](https://github.com/znuny/Znuny/files/7337829/changes.zip)

Have fun! 

### Screenshots
![linkobject](https://user-images.githubusercontent.com/2903042/137126494-74c78c95-149a-42ec-af9f-ca5de3ad8109.png)

**Comment by rkaldung** [comment]
@falkos I'll close this issues since this feature request is already mentioned in the CHANGES.md of the upcoming version: https://github.com/znuny/Znuny/blob/rel-6_4-dev/CHANGES.md#641-2022--
