### ISSUE TITLE
Feature Request: Extend possible note length in Generic Agent

### ISSUE THREAD

**Issue by dpalic** [znuny/znuny-feature-requests#12]
right now we use the notes to add instructions for agents by generic agents.
Sadly if you have long links, many of the possible 200 chars of the ticket notes are already gone.

imho: this was a good decision in the early and mid 2000, but nowadays field length shall not be an issue anymore.

It would be great to have both
- a default of 1000 chars (prio1)
- and ideally a configurable length by installation instance (prio2)

**Comment by rkaldung** [comment]
Hi @dpalic , we don't see really a need for this because a functionality to create articles already exists. This is a typical use case to create process tickets where you can use the transition action ArticleCreate.
