### ISSUE TITLE
Feature Request – Allow agents who are not owner or responsible to mark articles as important

### ISSUE THREAD

**Issue by KaiHerlemann** [znuny/znuny-feature-requests#13]
Hi,

I'd like request a sysconfig option to allow agents who aren't owner or responsible person to mark an article as important.
I think "mark as important" is a good possibility to get an overview about the ticket, for the ticket owner and the responsible person, and for other agents too. So we would be glad if such a feature would be added.

Thanks,
Kai

**Comment by rkaldung** [comment]
Hello @KaiHerlemann,

We do not see a valid use case here. If your workflow rely on this change we we recommend using a custom file with a change to implement this:

1. Copy the file Kernel/Output/HTML/ArticleAction/MarkAsImportant.pm to Custom/Kernel/Output/HTML/ArticleAction/MarkAsImportant.pm
2. Comment the lines https://github.com/znuny/Znuny/blob/dev/Kernel/Output/HTML/ArticleAction/MarkAsImportant.pm#L47 - 59
3. Make you life for updates easier and and package this change (and other if there are some), find more about it in our [manual](https://doc.znuny.org/manual/developer/extending/package-building.html)
