### ISSUE TITLE
Feature Request: Generic agent fields shall be configurable as text search or RegEx search

### ISSUE THREAD

**Issue by dpalic** [znuny/znuny-feature-requests#14]
afaik right now the Generic Agent fields are simple _like %_ searches. This makes it impossible to define more complex searches like it is possible on postmaster filter

So the feature request here is to be able to use regular expressions in the generic agent fields, so the GA would be able to handle or conditions and more sophisticated operations too, which are provided by GA.
E.g. it would be possible to have one GA, which is matching multiple e-mail addresses or multiple different subjects.

an idea could be to have a check box beside the reasonable fields like shown in screenshots. So it is easier to identify what type of SQL query to use, since the user provides the data and no parser will be required.

**preconditions:**

- the checkbox fields only appear if the database is capable of regex (afaik all supported DBs are)

![Screenshot_02543](https://user-images.githubusercontent.com/1399203/140069244-1e6e736f-c845-46cf-928b-b7a62abbf706.png)

**Comment by rkaldung** [comment]
This issues is closed because it is nearly a duplicate if https://github.com/znuny/znuny-feature-requests/issues/5. Please check the other feature request for being updated.
