### ISSUE TITLE
Feature-request: Make confidential information unreadable

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/znuny-feature-requests#15]
I need a way that confidential information that an agent sends to the ticket maker can only be read by the ticket maker. In the article overview, the confidential information could be seen as asterisks. To achieve this, the agent could embed the information to be protected in special markers when composing the outgoing message. Znuny could remove these markings before sending. For the article to be created, the markings could be removed and the information between the markings could be replaced with asterisks. In this way, the sent confidential messages are protected from being viewed by agents and the privacy of personal information is guaranteed.

In my specific case, I helped me with an announcement to the ticket creator via the ticket system that I will send him a separate email outside of the ticket system with his new access data, so that the access data is only visible to him. All agents in the ticket system can only see this announcement, but not his personal access data.

**Comment by rkaldung** [comment]
Hi @schnudd31do3, we did not found a common use case for your described scenario. Since "confidential data" could be everything different in every user's situation we don't see a common implementation. If you really require such a feature, custom development is our recommended way.

**Comment by schnudd31do3** [comment]
Hi @rkaldung, I understand your decision. But, if innovations were only recognized when many people had the same requirement, mankind would probably not have gotten as far as it actually is.

My intention was to point to a **principle question** affecting the whole ticketsystem, using my concrete case: **How to protect private information?**

I wrote that I found a way outside of the ticketing system, but it's not particularly elegant. It would be better if the ticket system offered me an integrated solution. As a possible concrete solution, I could also imagine that there could be another text formatting option in addition to "Bold", etc. in the text windows, which only shows the text to be protected to the recipient.

You are welcome to discuss again whether such a feature is necessary and useful in terms of data protection.

**Comment by hanneshal** [comment]
Hi @schnudd31do3 
I just want to point out, this is not a decision of one person (@rkaldung), this was a team discussion and decision. 

If you have the special need to send confidential information and don't want to show it to other users, Znuny is not the perfect tool at the moment. This feature just wont fit in the current and future stage of the product development. 

There are many ways to solve this situation at the moment, but might not fit your use case:
- Delete an article after sending
- Use a separate ticket and modify your permissions accordingly (Queue or a custom permission module)
- Use encryption and personal user keys

You suggestions may be fine for you, but wont improve the use-case for 80-90% of the cases we like do deal with. 
The cost:use ratio is a very relevant one for our small product. 
If we drop 10 days into days (just a sample) we are in about ~12k EUR without any specials. And thats an amount of time and therefore money we can't spent for this idea. Sponsoring / Custom development is possible, but as it is off now we don't implement this.

Hope this is a more complete answer. Even if it is not satisfactory for you at the moment.

Regards
Johannes
