### ISSUE TITLE
Bulk Action Templates

### ISSUE THREAD

**Issue by dignin** [znuny/znuny-feature-requests#18]
Performing bulk actions which are recurring tasks requires much repetitive work.

As an agent, I would like to create bulk action templates allowing me to quickly sort spam and close messages, categorize multiple tickets, add a standard note while dispatching to new queues, or just for a quick merge to oldest.

As a manager, I want to be able to distribute bulk action templates to my teams based upon their roles or queues.

As an administrator, I want to limit access to who can create, use and share templates.

**Comment by rkaldung** [comment]
## Discussion
- macro functionality
- Apply macros in AgentTicketBulk

Closes for now/postponed
