### ISSUE TITLE
TicketArticleCreate: In the Body-field, show the value of a DynamicFieldVariable instead of its key

### ISSUE THREAD

**Issue by schnudd31do3** [znuny/znuny-feature-requests#39]
When automatically creating an article with a DynamicFieldVariable for the body, without my modification it only shows the key of it. **But my modification shows the value instead of the key, which is more human readable.**

My example for a DynamicFieldVariable "XXXClassifyHelp":
![image](https://user-images.githubusercontent.com/72391822/203929679-4b56695b-2a07-4f11-b81a-9ff2a2f026a9.png)
One of its keys is "XXXHlpBug", its value is "Bug"

My transition action uses TicketArticleCreate to automatically create a note with the content of a DynamicFieldVariable
![image](https://user-images.githubusercontent.com/72391822/203930318-35628b5d-55d0-4b50-8cd0-8ef19ec5b276.png)

With my extension the body of the note shows "Bug" instead of "XXXHlpBug", which is more human readable.
![image](https://user-images.githubusercontent.com/72391822/203934676-663d2922-5123-4461-ab67-b9065bdc6f64.png)

My piece of code in TicketArticleCreate.pm, line ~229:
![image](https://user-images.githubusercontent.com/72391822/203931929-0acb80b9-54d6-4bb6-b6b7-227394e93f7f.png)
Insertion between the "###" marks. Commented-out line with "#".

**Comment by hanneshal** [comment]
Just a question:
before your patch, have you tried <OTRS_TICKET_DYNAMICFIELD_BLUB_VALUE> ?
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/804939/203949919-5f7df18e-2db9-4ba0-a253-43492c510577.png">

?

**Comment by schnudd31do3** [comment]
Great job 😊, thanks. I did not know the (new?) feature. It did what I need.

BTW:
Is it somehow possible to place additional fixed string to it?
E. g. "<OTRS_TICKET_DynamicField_xyz_Value> dummy" 
result:
 "[value of DynamicField_xyz] dummy"

**Comment by hanneshal** [comment]
This is at least available since OT** 5

You can just pass a string after the placeholder. This should work for the body tag without problems

**Comment by schnudd31do3** [comment]
Thanks.
