### ISSUE TITLE
Show DynamicField Name+Label in Generic Agent and Notifications

### ISSUE THREAD

**Issue by hanneshal** [znuny/znuny-feature-requests#40]
It would be helpful to show the DynamicField Name and the Label in the settings for a generic agent+notifications.

When using processes it is often necessary to use the same label, but a different name. When one needs to access this in GA or a ticket notification, it gets confusing really fast.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/804939/204506281-2dc6973b-4609-4582-b1a1-65ebfa18119e.png">

**Comment by dignin** [comment]
Should this also be in Agent|Customer search?

**Comment by hanneshal** [comment]
> Should this also be in Agent|Customer search?

No. The GA Interface is enough here
Thanks

**Comment by rkaldung** [comment]
internal issue 866

**Comment by rkaldung** [comment]
This feature request will be part of Znuny 7.1.1
