### ISSUE TITLE
A new setting for a custom favicon (product.ico)

### ISSUE THREAD

**Issue by cristalink** [znuny/znuny-feature-requests#47]
It would be great to be able to specify the path to a custom favicon (aka shortcut icon). It's currently hardcoded in many places like this:

`<link rel="shortcut icon" href="[% Config("Frontend::ImagePath") %]icons/product.ico" type="image/ico" />`

It's unfeasible to override _Frontend::ImagePath_ because this path contains many other images which don't need to be changed.

Currently, the only way to change the icon is to replace product.ico on every update.

Thanks!

**Comment by rkaldung** [comment]
Internal issue 864

**Comment by NiklasSchmitt** [comment]
shortcut icon and Apple touch icon will be configurable within Znuny 7.1.1. See commit https://github.com/znuny/Znuny/commit/659192f8fb7afdba7796912029c9e4bf12341368 for technical details.
