### ISSUE TITLE
Dark mode Skin

### ISSUE THREAD

**Issue by nodrogneirbo** [znuny/znuny-feature-requests#49]
Many of my agents who use Znuny all day are requesting a dark mode skin (dark - not black) to soften the screen glare. This seems more problematic with the sparse new v7 GUI as there is more white-space on screen.

**Comment by hanneshal** [comment]
Hi @nodrogneirbo 
this is already on the list. 
When we fixed the more pressing issue we can move to the comfort ones.

**Comment by BurtGummer** [comment]
Is there a dark mode skin for Znuny 6? Otherwise I would also request it as a feature.

**Comment by rkaldung** [comment]
Internal issue 860

**Comment by rkaldung** [comment]
A dark mode is included in Znuny 7.1, the open-source add-on Znuny-ExtraSkins provides a slim skin for 7.1 too.
The add-ons Znuny-ExtraSkins will provide a slim skin and a slim-dark skin for 7.0.

**Comment by nnekipelov** [comment]
Znuny-Additional skins did not work in Znuny 7.1.2

**Comment by rkaldung** [comment]
> Znuny-Additional skins did not work in Znuny 7.1.2

What exactly is not working?

**Comment by nnekipelov** [comment]
I tried to copy the package to the znuny folder and then executed the following commands:

su znuny -s /bin/bash -c "/opt/znuny/bin/znuny.Console.pl Maint::Config::Rebuild"
su znuny -s /bin/bash -c "/opt/znuny/bin/znuny.Console.pl Maint::Cache::Delete"
su znuny -s /bin/bash -c "/opt/znuny/bin/znuny.Console.pl Maint::Loader::CacheCleanup"
systemctl restart httpd

Then I was able to see the new items in the list of skins to choose from in the user settings, but switching does not give the desired result.

--
Best regards, Nick

**Comment by hanneshal** [comment]
Then please move the corresponding GitRepo and open an issue there. 
Incl the required stuff.

Please also note: dark skin is not part of the Extra Skins. There will be a dark-slim, I think next week, but this is not included at the moment.

Regards
