### ISSUE TITLE
Use fullname for user mention label

### ISSUE THREAD

**Issue by tgurr** [znuny/znuny-feature-requests#51]
Followup of https://github.com/znuny/Znuny/pull/436 as requested by https://github.com/znuny/Znuny/pull/436#issuecomment-1556982580 though I'd rather consider this an actual fix to an existing problem rather than a real request for a feature. Anyways as I was unable to solve this myself as it's not enough to just change the variable either in the code directly (see my failed attempt at https://github.com/znuny/Znuny/pull/436) or via sysconfig as it'll result in:

* no mention notification emails being sent anymore
* timestamp of tickets in the mention dashboard main widgets are not being updated anymore
* maybe even more fallout(?)

## Proposed change
Change the displayed username to fullname to be more useful and to bring it in line with what is shown in the mentions widget.

For example in our company the username can be quite meaningless/cryptic so if you mention multiple persons like:

@user1 check network
@user2 check firewall

it would end up being problematic to identify which person is actually meant as it would result in something like:

![image](https://github.com/znuny/Znuny/assets/414984/1b174d30-0584-4427-b5a8-7f22154e3c7e)

While with changing it to fullname it'll read:

![image](https://github.com/znuny/Znuny/assets/414984/3f692eae-b9a1-4710-bfe5-f7ba0a79ff11)

which also brings it in line with the mentions shown in the mentions widget where fullname is already being used:

![image](https://github.com/znuny/Znuny/assets/414984/c72d4731-56af-4867-8b8a-e2123595ef6f)

**Comment by rkaldung** [comment]
The full name will be defined by the value of the system configuration `FirstnameLastnameOrder`.

**Comment by rkaldung** [comment]
Internal issue 863

**Comment by rkaldung** [comment]
@tgurr This feature will be released with Znuny 7.1.1

**Comment by tgurr** [comment]
@rkaldung thanks! Any chance this will get backported to 6.5 LTS?

**Comment by rkaldung** [comment]
@tgurr I'm sorry, but this has not been planned. Maybe it's worth a try to check the commit if you really need this and add the changed to your Custom/  folder.
