### ISSUE TITLE
Mark E-Mails as high/low important for recipients 

### ISSUE THREAD

**Issue by makeitthingsbetter** [znuny/znuny-feature-requests#58]
### User story: 
Agents would like to mark important, outgoing mails from znuny to customers or other recipients as “high important”. In MS Outlook these mails would show a red exclamation mark. 

### Situation:
It is possible to check the “x-priority” mail header for incoming mails with a postmaster filter. But for outgoing mails it is not possible to set this header / importance.

### Desired Goal: 
In every GUI (for writing mails) there should be a button to set the priority for the mail. X-Priority header would be set to 1, if “high importance” is selected.
If necessary, also “low importance” with X-Priority header = 5 or “default” with cleared X-Priorty header could be done with a dropdown list. 
![grafik](https://github.com/znuny/znuny-feature-requests/assets/66119629/e645d2a5-3339-4c96-829d-33366c7ac36d)

### Impact:
Agents would see a new button to set the mail priority. 
With a SysConfig Setting this button could be hidden. 
Recipients would see the importance of the mail.

**Comment by rkaldung** [comment]
This feature is added to the roadmap. There might be a slight change possible. We discuss the option to use the ticket's priority and map it to the value for the X-Priority header.

**Comment by rkaldung** [comment]
Internal issue 862

**Comment by rkaldung** [comment]
@makeitthingsbetter This feature will be part of Znuny 7.1.1
