### ISSUE TITLE
Feature - The ticket visual notifications in toolbar dont refresh if i set autorefresh in personal preferences.

### ISSUE THREAD

**Issue by iwillforce** [znuny/znuny-feature-requests#7]
### Environment

- OS:           Windows 11 Pro
- Browser:      Chrome 96
- Znuny version: 6.0.29

### Expected behaviour

When i set overview refresh time in personal preferences, ticket visual notifications in toolbar must be refreshed as well.

### Actual behaviour

Ticket visual notifications in toolbar are not getting updated when autorefresh is triggred.

### How to reproduce

1. We set this refresh interval time in personal preferences on each agent
![148193452-2115621d-4137-4167-8600-563d9ab39fbf](https://user-images.githubusercontent.com/33241171/148369517-41f0b8d4-96bf-4045-b94a-3efa2bfa519b.png)
2. Issue in action
![12](https://user-images.githubusercontent.com/33241171/148369582-7b21577e-bc24-4f80-b674-9563e3677b37.gif)

### Additional information

This icons only refreshed if i type manually F5 or CMD+R.

**Comment by jepf** [comment]
This is part of Znuny 6.4.1.
