### ISSUE TITLE
Feature Request: Colorify statuses

### ISSUE THREAD

**Issue by dpalic** [znuny/znuny-feature-requests#8]
right now the table view of the tickets is sadly only gray/white

it would be great to be able to define colors per status of a ticket.
e.g. if you define a status like "clientReplied" (under /otrs/index.pl?Action=AdminState;Subaction=Change;ID=xy) it would be great to make these tickets colored. So the color could look like this:
![Screenshot_02551](https://user-images.githubusercontent.com/1399203/140508945-82640380-9de9-42e6-8e73-367b1bd60a3e.png)

the UI could look like
![Screenshot_02552](https://user-images.githubusercontent.com/1399203/140509240-0cedf796-e3f8-4f68-96d9-1d56e2596aeb.png)

**Comment by rkaldung** [comment]
Hello @dpalic,

This feature request won't be accepted because a similar feature is planned for the upcoming UI changes. Until then, I suggest to use the mentioned add-on.
